spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t84HZ1UFh2gdEoE9hTM
      secret-key: DfExIyTasdkupONZVCX84sXlStd7gS
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
  application:
    name: gulimall-third-party
server:
  port: 11000